name: myfirstproject
services:
	
 mysql:  # MySQL database service
    image: mysql:5.7  # Use the MySQL 5.7 image
    container_name: mysql  # Name the container "mysql"
    environment:  # Environment variables for MySQL
      MYSQL_ROOT_PASSWORD: 123456  # Root password for MySQL
      MYSQL_DATABASE: database  # Name of the database to create
      MYSQL_USER: wordpressuser  # User for WordPress to connect
      MYSQL_PASSWORD: password  # Password for the WordPress user
    volumes:
      - db_data:/var/lib/mysql  # Persist MySQL data in a Docker volume
    networks:
      - default  # Connect to the default network

  phpmyadmin:  # phpMyAdmin service for managing MySQL
    image: phpmyadmin/phpmyadmin  # Use the phpMyAdmin image
    container_name: phpmyadmin  # Name the container "phpmyadmin"
    environment:  # Environment variables for phpMyAdmin
      PMA_HOST: mysql  # Hostname of the MySQL server
      MYSQL_ROOT_PASSWORD: 123456  # Root password for MySQL
    ports:
      - 8080:80  # Map port 8080 on the host to port 80 in the container
    networks:
      - default  # Connect to the default network
    depends_on:  # Ensure MySQL starts before phpMyAdmin
      - mysql

  myfirstproject:  # WordPress service - change to your project name
    image: wordpress  # Use the WordPress image
    container_name: myproject  # Name the container "myproject"
    environment:  # Environment variables for WordPress
      WORDPRESS_DB_USER: wordpressuser  # MySQL user for WordPress
      WORDPRESS_DB_PASSWORD: password  # MySQL password for WordPress
      WORDPRESS_DB_NAME: database  # Database name for WordPress
      WORDPRESS_DB_HOST: mysql  # Hostname of the MySQL server
      WORDPRESS_DEBUG: 1  # Enable debugging in WordPress (set to 0 in production)
    volumes:
      - "./myfirstproject/web:/var/www/html"  # Map local directory to container
    ports:
      - "80:80"  # Map port 80 on the host to port 80 in the container
    networks:
      - default  # Connect to the default network
    depends_on:  # Ensure MySQL starts before WordPress
      - mysql

volumes:
  db_data:  # Define a volume for MySQL data
    name: myproject_db  # Name the volume

networks:
  default:  # Define the default network
    driver: bridge  # Use the bridge network driver for local development